/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MinhasColetasRouteImport } from './routes/minhas-coletas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ColetaRouteImport } from './routes/coleta'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosNovoRouteImport } from './routes/eventos.novo'
import { Route as EventosEventoIdRouteImport } from './routes/eventos.$eventoId'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasColetasRoute = MinhasColetasRouteImport.update({
  id: '/minhas-coletas',
  path: '/minhas-coletas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ColetaRoute = ColetaRouteImport.update({
  id: '/coleta',
  path: '/coleta',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosNovoRoute = EventosNovoRouteImport.update({
  id: '/eventos/novo',
  path: '/eventos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventoIdRoute = EventosEventoIdRouteImport.update({
  id: '/eventos/$eventoId',
  path: '/eventos/$eventoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atividades': typeof AtividadesRoute
  '/cadastro': typeof CadastroRoute
  '/coleta': typeof ColetaRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/minhas-coletas': typeof MinhasColetasRoute
  '/ranking': typeof RankingRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/eventos/': typeof EventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atividades': typeof AtividadesRoute
  '/cadastro': typeof CadastroRoute
  '/coleta': typeof ColetaRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/minhas-coletas': typeof MinhasColetasRoute
  '/ranking': typeof RankingRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/eventos': typeof EventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/atividades': typeof AtividadesRoute
  '/cadastro': typeof CadastroRoute
  '/coleta': typeof ColetaRoute
  '/dashboard': typeof DashboardRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/minhas-coletas': typeof MinhasColetasRoute
  '/ranking': typeof RankingRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/eventos/novo': typeof EventosNovoRoute
  '/eventos/': typeof EventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/atividades'
    | '/cadastro'
    | '/coleta'
    | '/dashboard'
    | '/grupos'
    | '/login'
    | '/minhas-coletas'
    | '/ranking'
    | '/eventos/$eventoId'
    | '/eventos/novo'
    | '/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/atividades'
    | '/cadastro'
    | '/coleta'
    | '/dashboard'
    | '/grupos'
    | '/login'
    | '/minhas-coletas'
    | '/ranking'
    | '/eventos/$eventoId'
    | '/eventos/novo'
    | '/eventos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/atividades'
    | '/cadastro'
    | '/coleta'
    | '/dashboard'
    | '/grupos'
    | '/login'
    | '/minhas-coletas'
    | '/ranking'
    | '/eventos/$eventoId'
    | '/eventos/novo'
    | '/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AtividadesRoute: typeof AtividadesRoute
  CadastroRoute: typeof CadastroRoute
  ColetaRoute: typeof ColetaRoute
  DashboardRoute: typeof DashboardRoute
  GruposRoute: typeof GruposRoute
  LoginRoute: typeof LoginRoute
  MinhasColetasRoute: typeof MinhasColetasRoute
  RankingRoute: typeof RankingRoute
  EventosEventoIdRoute: typeof EventosEventoIdRoute
  EventosNovoRoute: typeof EventosNovoRoute
  EventosIndexRoute: typeof EventosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-coletas': {
      id: '/minhas-coletas'
      path: '/minhas-coletas'
      fullPath: '/minhas-coletas'
      preLoaderRoute: typeof MinhasColetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleta': {
      id: '/coleta'
      path: '/coleta'
      fullPath: '/coleta'
      preLoaderRoute: typeof ColetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/novo': {
      id: '/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/eventos/novo'
      preLoaderRoute: typeof EventosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventoId': {
      id: '/eventos/$eventoId'
      path: '/eventos/$eventoId'
      fullPath: '/eventos/$eventoId'
      preLoaderRoute: typeof EventosEventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AtividadesRoute: AtividadesRoute,
  CadastroRoute: CadastroRoute,
  ColetaRoute: ColetaRoute,
  DashboardRoute: DashboardRoute,
  GruposRoute: GruposRoute,
  LoginRoute: LoginRoute,
  MinhasColetasRoute: MinhasColetasRoute,
  RankingRoute: RankingRoute,
  EventosEventoIdRoute: EventosEventoIdRoute,
  EventosNovoRoute: EventosNovoRoute,
  EventosIndexRoute: EventosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
